### ISSUE TITLE
Customize Theme css

### ISSUE THREAD

**Issue by marciomsm** [rmpestano/cukedoctor#89]
I am using Cucumber Living Documentation plugin and I would like to customize the theme. Is it possible?What is the best way to do that?

Thanks.

**Comment by rmpestano** [comment]
Hi @marciomsm, sorry for the late reply.

what kind of customization do you need? for structural changes cukedoctor may be feed with renderers (feature, step, etcc) via SPI, [see here](https://github.com/rmpestano/cukedoctor#customizing-your-living-documentation).

For look & feel it uses [predefined themes](https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-extension/src/main/resources/themes)  and for now there is no way you can provide one dynamically.

Note that for the SPI stuff work you need to execute Cukedoctor on your application because SPI uses the classpath to look for the renderers which I don't think is possible for Cucumber Living Documentation plugin.

For the theming thing on jenkins plugin an idea would be to have a (global) configuration option where user would upload a theme.

**Comment by marciomsm** [comment]
Hi @rmpestano I would like to change only the look & feel. Is there any way to change this more easily?

Thanks.

**Comment by rmpestano** [comment]
Currently there is no way but I will let this issue opened. What we need is to provide a way to Cukedoctor (and jenkins plugin) to read an external theme file. 

So when this issue becomes fixed you will be able to provide your theme.css, are you ok with this approach?

thank you for your feedback.

**Comment by marciomsm** [comment]
@rmpestano I agree with this approach. I believe that it will be a good improve. I need to customize the live documentation in my current project.

Thank you very much. I really appreciate your help.

**Comment by rmpestano** [comment]
Hi @marciomsm, see https://github.com/rmpestano/cukedoctor#customizing-your-living-documentation for customizing generated docs css and pdf. If you want to test right now It is available in [latest snapshot](https://github.com/rmpestano/cukedoctor#distribution).

**Comment by marciomsm** [comment]
Hi @rmpestano, sorry I didn't understand how can I customize docs CSS to jenkins plugin? Where I need to create the cukedoctor.css?

Thank you very much.

**Comment by rmpestano** [comment]
Hi @marciomsm,
quoting the readme:

> By default Cukedoctor will search (recursively) for the custom css in current directory but you can provide any path via system property named CUKEDOCTOR_CUSTOMIZATION_DIR.

So it depends from where you are executing cukedoctor, if it is via Maven plugin them the cukedoctor.css must be anywhere on your project (e.g src/test/resources).

If you are using cukedoctor-main it can be on the same forder where cukedoctor.jar is being run.
